sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks

env:
  global:
  - secure: "sEGO03i49UvnQefDUrWIWPIXH2kBl5tjiT0GdaY4187raProqpoIOAFCNveVyhyrY8g3fHA9GGXvTe9SQK3teXNSMbzRLVEF7zMB0rOT/xM2t4ffQIP4dlEwoEEQclFdQ3d1Ejwh9fpQREm2uZN4M7cyiHlxznhgAFnGP/Wdc7HiKpEwl45wA1fQ0zMyewxdFLrhKXIz57GyemCx/FDXJQnIkUIvOxA+539zD/1SJ+BzaMzILA3YpCi6Q42MZwtE/fjlzC8ctBwNgvWxkbmwLdB/MOJ1kemUZaOE27vFgxIc/U5clUC2wKorb4vOvzl/L7c5mY/zeGRLT93/TPMrQXivk30leUtuFpWxXQMhcXMggIVVPUnZNq7A98BLWhKdXWGIMEegYIgHhwDqtZjkmj9UDAs+JmuQlUP7VYK4tt9di3jP64ZkO8hsX98UcrxCAVWIirvrjUB84M7ovT6D9F1aJ90Y6b/n2f4e5TPx8nBVZzktS5Yne3crgtAg4t3ppy+vozRZLaQnRENTt5ycbTWZDW4qmXNbsyF2yC/5Gg2h7SE/d9AnmnrFEesFy5TPXAF81kLtMi87Hzcofis1BNog8W8wzODPWNMJRvtfNOaAuEaxQ61fVCAD+I9z4Lq13IG46L5MK1XPGiFzEFHSUBsRL6tB4PWH6t8QmKNqhI0="
  - secure: "AgTBsrUUShRF/VvAQHbDCd5pMQsVYR/wVfJ1UO83fGEAi/+cS6H2TORVwJhJHZgx2yCQAZDfWa1tvg4DZy8ndSOgcN2mqojwdvt1zBuKLzh1Gj2sNV1Wj/sLddpMFa/yNxXIITo0QQd5J+nL/rNEd8tWgZUsae18pfuIkPoN0iKMjwzQpf2AJzH3db6F1c9hiUuRurHKhHm/mgjw+PXE2xe9IEIF8QX+xZZUdpzJIWhktxawTjPVRq9PjWmdjocryJeK9GEOEJ18wn9eSIdl1ao9RqetC0L/xPgIkrtA24PkV0GtMffznnQTvsuq4y4TPcRIVnawNhMA7n0Lcr2xvwTAW0T1coUHVFQyMleoE8mBtZl2Hesi1OHBCVJ+yv/ooihiL703iM7ipL+Kkw4fah7flAzYzTdp5gR4yK4XZKWOw0mfdOh4bjlyuzAb7ATSsp45aaVikuen91V9ggLvCL9RTBxzd+5yx5To/+dQoWblOQdDCEh834IIunG2qdHNrzdY4p5jhJ9UQ8F1N57HnNFqAyU91uMgClmUjV/VdstDSHy2SzbORNBuug9PPPEOGE/6CPF0lF7wR4saHSV7/a/RGCMQXOsuR55FD9nOCH99FyY+DPBeMBKhr+5vsbdfcI3+r+VCEOywbgoAcOF8an7vvy59gcDg7mj//J8SAZU="
  - secure: "qvvZvmGxpjgwGh3g8HN6fU7T3/GsHOCQvKeHLfACN5OLpodKTkECzBTCQRQmDLgC10tYeT2CTyC+pUg3VvPOoYxAtN9ci+/K/OyjWwh6Kgpp26WC+/sKzUn+p8ntZnMdwA57TnCvukdsI73xUjEVq2dl057fTbBdSIDbkqiYoMVArDhjlDGafathfLaEJhv7JAoKx0nYppcYBoReD5Em6cpjKF+wVxaJ1RoIhHjPB964TkhrOeTCwI2Bm+e/y0uDARY0WmdAXJs5PU1NHrJel/PXPMPMAmsgGKGAwcp85gTQPdNx8308YVoPdEGamwpdRBSIcXIJcZSJnkMU+veZXXVM0ao/HC3s5W7+pibpQwGEPj97enmJl+z//9FBOhetilFm5crDu4vmJlYSSq2aEWFqCMX/nC3lZLrUUAui8Tc+10wJQ1qkTHon/tn+jtq3sLoVz9wAFyoedlhcGJsaKzoNE5CCZv9XD5PMR1WiONBhb7/ZUEoYXd+HtCEjpN+nEKKc8ywxwFSuVf+kUOgLxHWStJa7f0m4eOYmLvj/mrrBWZ17aVDssgEg0ML5qaCfAuyf2KvCu8uVoO0lY9oWGbBrVfksReM8FvS892bYbPC8jkIM+GUoOvcLPzDkSysBcOyTDUEsYu7w500a+KrBe29DTTaKsIHGeHQna8TthrU="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
