sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks

env:
  global:
  - secure: "Wl4GNPo60W/2v0yz8sIOb9L4RrwISaHtVrn22yesT/erG6UT5jHzEyBfb0RO6wWJ/FMMOewmsN585duBFrrprObqyerlvHIHBcSMt53u0b0uonTXtXgqy7Zbs0kOCRu7gPAPRx1ulD1eNQQ+cd2ogeik5BHaWhUzHP3/gW99596mVvSblk4nWvcJPXWK9qZyKZNyjl8nEvPTuOtHoC86rHTieXIMlaSRUY6qOGoIgG392oXH4Y27+3h/ho2EuJGdrCpytnlF5vb3SVGM8vCAzD+ue/HRuKCxi/rscbrGDO3FUPas1X/E/bmfqe1eVcSalbonSkuiwPPdGP6I94qGCP68wuZ+W1CpmH/LT/SdqKTQcp6wzfGMIG+vgOW5FSqilkXvj49VqNPZfZOpaH+OKED7QhL3ypZY4jKgyQbPJBpfZ5aNkNhMtYSfNPNF0+HRXjBaJC1Uwin13YkgNHRQpJFojIzyJr+Z9X9H8X/x6EbKXveht81xwmxM3q88eCM3VMFT2u1tq2eddy9SAlbYipN2IdJrjyaRsheMbb8I1HK+xmDrAzuWISh5r4cF7E/27DZwp1FbPSL+tsWqIGH/SrqW3PUck94W0P3m7qX0vlaXJDC9vKc/tLqysq12Vlnu3bp3QCCxr4VVqpJfuh5R1c12iQR/RNujich/dkJQLQs="
  - secure: "AgTBsrUUShRF/VvAQHbDCd5pMQsVYR/wVfJ1UO83fGEAi/+cS6H2TORVwJhJHZgx2yCQAZDfWa1tvg4DZy8ndSOgcN2mqojwdvt1zBuKLzh1Gj2sNV1Wj/sLddpMFa/yNxXIITo0QQd5J+nL/rNEd8tWgZUsae18pfuIkPoN0iKMjwzQpf2AJzH3db6F1c9hiUuRurHKhHm/mgjw+PXE2xe9IEIF8QX+xZZUdpzJIWhktxawTjPVRq9PjWmdjocryJeK9GEOEJ18wn9eSIdl1ao9RqetC0L/xPgIkrtA24PkV0GtMffznnQTvsuq4y4TPcRIVnawNhMA7n0Lcr2xvwTAW0T1coUHVFQyMleoE8mBtZl2Hesi1OHBCVJ+yv/ooihiL703iM7ipL+Kkw4fah7flAzYzTdp5gR4yK4XZKWOw0mfdOh4bjlyuzAb7ATSsp45aaVikuen91V9ggLvCL9RTBxzd+5yx5To/+dQoWblOQdDCEh834IIunG2qdHNrzdY4p5jhJ9UQ8F1N57HnNFqAyU91uMgClmUjV/VdstDSHy2SzbORNBuug9PPPEOGE/6CPF0lF7wR4saHSV7/a/RGCMQXOsuR55FD9nOCH99FyY+DPBeMBKhr+5vsbdfcI3+r+VCEOywbgoAcOF8an7vvy59gcDg7mj//J8SAZU="
  - secure: "qvvZvmGxpjgwGh3g8HN6fU7T3/GsHOCQvKeHLfACN5OLpodKTkECzBTCQRQmDLgC10tYeT2CTyC+pUg3VvPOoYxAtN9ci+/K/OyjWwh6Kgpp26WC+/sKzUn+p8ntZnMdwA57TnCvukdsI73xUjEVq2dl057fTbBdSIDbkqiYoMVArDhjlDGafathfLaEJhv7JAoKx0nYppcYBoReD5Em6cpjKF+wVxaJ1RoIhHjPB964TkhrOeTCwI2Bm+e/y0uDARY0WmdAXJs5PU1NHrJel/PXPMPMAmsgGKGAwcp85gTQPdNx8308YVoPdEGamwpdRBSIcXIJcZSJnkMU+veZXXVM0ao/HC3s5W7+pibpQwGEPj97enmJl+z//9FBOhetilFm5crDu4vmJlYSSq2aEWFqCMX/nC3lZLrUUAui8Tc+10wJQ1qkTHon/tn+jtq3sLoVz9wAFyoedlhcGJsaKzoNE5CCZv9XD5PMR1WiONBhb7/ZUEoYXd+HtCEjpN+nEKKc8ywxwFSuVf+kUOgLxHWStJa7f0m4eOYmLvj/mrrBWZ17aVDssgEg0ML5qaCfAuyf2KvCu8uVoO0lY9oWGbBrVfksReM8FvS892bYbPC8jkIM+GUoOvcLPzDkSysBcOyTDUEsYu7w500a+KrBe29DTTaKsIHGeHQna8TthrU="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
